### ISSUE TITLE
zypper refs -r silently blocking on GPG validation with --root

### ISSUE THREAD

**Issue by cbosdo** [SUSE/connect#121]
Run SUSEConnect with --root param:

```
SUSEConnect -p SLES/12-0/x86_64 --root /srv/container3 -r XXXXX
```

It silently blocks on zypper refresh-services -r asking for the GPG key to be validated / refused.

Expected behavior:
- ask the user what to do
- add options like zypper's _--no-gpg-checks_ / _--gpg-auto-import_ to allow silent script execution

**Comment by ngetahun** [comment]
@cbosdo Is the issue still there? Otherwise I will go ahead and close this.

**Comment by cbosdo** [comment]
Closing... not using it anymore
