### ISSUE TITLE
Missing mock in tests, /etc/SUSEConnect is read from the current system

### ISSUE THREAD

**Issue by lslezak** [SUSE/connect#149]
If `/etc/SUSEConnect` does not exist in the system the tests run correctly.

If you create `/etc/SUSEConnect` file with some configuration, for example:

``` yaml

---
url: https://foo.suse.com
insecure: false
```

Then the tests fail:

```
  1) SUSE::Connect::Client.new empty_opts should set url to default_url
     Failure/Error: subject.url.should eq subject.class::DEFAULT_URL

       expected: "https://scc.suse.com"
            got: "https://foo.suse.com"
```

The config file from system was read instead of using the default.

**Comment by ngetahun** [comment]
@lslezak Thanks for reporting this. Can you elaborate on how to reproduce the failure?
